### ISSUE TITLE
Inserting Query Args

### ISSUE THREAD

**Issue by j-crowe** [stealthycoin/query-args-as-a-service#1]
There needs to be a way to insert some query args

**Comment by j-crowe** [comment]
### Definitely needs to handle query args

**Comment by j-crowe** [comment]
## It should handle query args too probably

**Comment by j-crowe** [comment]
# Absolutely needs to handle query args

**Comment by j-crowe** [comment]
# BUMP

**Comment by j-crowe** [comment]
# BUMP

**Comment by j-crowe** [comment]
# Any solution yet @stealthycoin ?

**Comment by j-crowe** [comment]
# _**BUMP**_

**Comment by stealthycoin** [comment]
bump need this too

**Comment by stealthycoin** [comment]
You can now perform a complex query to query conversion:

```
$ curl "https://r6i5b3yao2.execute-api.us-west-2.amazonaws.com/dev/query-2-query?key=value"
key=value
```

**Comment by stealthycoin** [comment]
@j-crowe got this ALL SOLVED UP
